/// Il catalogo dei ritratti: quali file, e dove sta la testa in ognuno.
///
/// GENERATO dalla plancia — non si scrive a mano. Le misure sono quelle prese
/// in fase di costruzione dei render: dove sta la testa in ogni immagine, che
/// e' quello che serve per incollare la testa scelta sul busto scelto.
library;

/// Il lato della tela di ogni render.
const double latoDelRitratto = 192;

/// Dove sta la testa in un'immagine: il centro, il bordo di sopra, e quanto
/// e' larga. In punti della tela, non in frazioni.
typedef MisuraDellaTesta = ({double cx, double alto, double largo});

const misureDeiRitratti = <String, MisuraDellaTesta>{
  'man_light': (cx: 95.5, alto: 12, largo: 141),
  'man_medium_light': (cx: 95.5, alto: 12, largo: 141),
  'man_medium': (cx: 95.5, alto: 12, largo: 141),
  'man_medium_dark': (cx: 95.5, alto: 12, largo: 141),
  'man_dark': (cx: 95.5, alto: 12, largo: 141),
  'man_beard_light': (cx: 95.5, alto: 12, largo: 141),
  'man_beard_medium_light': (cx: 95.5, alto: 12, largo: 141),
  'man_beard_medium': (cx: 95.5, alto: 12, largo: 141),
  'man_beard_medium_dark': (cx: 95.5, alto: 12, largo: 141),
  'man_beard_dark': (cx: 95.5, alto: 12, largo: 141),
  'man_curly_hair_light': (cx: 95.5, alto: 7, largo: 129),
  'man_curly_hair_medium_light': (cx: 95.5, alto: 7, largo: 129),
  'man_curly_hair_medium': (cx: 95.5, alto: 7, largo: 129),
  'man_curly_hair_medium_dark': (cx: 95.5, alto: 7, largo: 129),
  'man_curly_hair_dark': (cx: 95.5, alto: 7, largo: 129),
  'man_red_hair_light': (cx: 95.5, alto: 12, largo: 141),
  'man_red_hair_medium_light': (cx: 95.5, alto: 12, largo: 141),
  'man_red_hair_medium': (cx: 95.5, alto: 12, largo: 141),
  'man_red_hair_medium_dark': (cx: 95.5, alto: 12, largo: 141),
  'man_red_hair_dark': (cx: 95.5, alto: 12, largo: 141),
  'man_white_hair_light': (cx: 95.5, alto: 12, largo: 141),
  'man_white_hair_medium_light': (cx: 95.5, alto: 12, largo: 141),
  'man_white_hair_medium': (cx: 95.5, alto: 12, largo: 141),
  'man_white_hair_medium_dark': (cx: 95.5, alto: 12, largo: 141),
  'man_white_hair_dark': (cx: 95.5, alto: 12, largo: 141),
  'man_blonde_hair_light': (cx: 95.5, alto: 12, largo: 141),
  'man_blonde_hair_medium_light': (cx: 95.5, alto: 12, largo: 141),
  'man_blonde_hair_medium': (cx: 95.5, alto: 12, largo: 141),
  'man_blonde_hair_medium_dark': (cx: 95.5, alto: 12, largo: 141),
  'man_blonde_hair_dark': (cx: 95.5, alto: 12, largo: 141),
  'man_bald_light': (cx: 95.5, alto: 27, largo: 135),
  'man_bald_medium_light': (cx: 95.5, alto: 27, largo: 135),
  'man_bald_medium': (cx: 95.5, alto: 27, largo: 135),
  'man_bald_medium_dark': (cx: 95.5, alto: 27, largo: 135),
  'man_bald_dark': (cx: 95.5, alto: 27, largo: 135),
  'woman_light': (cx: 95, alto: 12, largo: 156),
  'woman_medium_light': (cx: 95, alto: 12, largo: 156),
  'woman_medium': (cx: 95, alto: 12, largo: 156),
  'woman_medium_dark': (cx: 95, alto: 12, largo: 156),
  'woman_dark': (cx: 95, alto: 12, largo: 156),
  'woman_beard_light': (cx: 95, alto: 12, largo: 156),
  'woman_beard_medium_light': (cx: 95, alto: 12, largo: 156),
  'woman_beard_medium': (cx: 95, alto: 12, largo: 156),
  'woman_beard_medium_dark': (cx: 95, alto: 12, largo: 156),
  'woman_beard_dark': (cx: 95, alto: 12, largo: 156),
  'woman_curly_hair_light': (cx: 93.5, alto: 9, largo: 161),
  'woman_curly_hair_medium_light': (cx: 93.5, alto: 9, largo: 161),
  'woman_curly_hair_medium': (cx: 93.5, alto: 9, largo: 161),
  'woman_curly_hair_medium_dark': (cx: 93.5, alto: 9, largo: 161),
  'woman_curly_hair_dark': (cx: 93.5, alto: 9, largo: 161),
  'woman_red_hair_light': (cx: 95, alto: 12, largo: 156),
  'woman_red_hair_medium_light': (cx: 95, alto: 12, largo: 156),
  'woman_red_hair_medium': (cx: 95, alto: 12, largo: 156),
  'woman_red_hair_medium_dark': (cx: 95, alto: 12, largo: 156),
  'woman_red_hair_dark': (cx: 95, alto: 12, largo: 156),
  'woman_white_hair_light': (cx: 95, alto: 12, largo: 156),
  'woman_white_hair_medium_light': (cx: 95, alto: 12, largo: 156),
  'woman_white_hair_medium': (cx: 95, alto: 12, largo: 156),
  'woman_white_hair_medium_dark': (cx: 95, alto: 12, largo: 156),
  'woman_white_hair_dark': (cx: 95, alto: 12, largo: 156),
  'woman_blonde_hair_light': (cx: 95, alto: 12, largo: 156),
  'woman_blonde_hair_medium_light': (cx: 95, alto: 12, largo: 156),
  'woman_blonde_hair_medium': (cx: 95, alto: 12, largo: 156),
  'woman_blonde_hair_medium_dark': (cx: 95, alto: 12, largo: 156),
  'woman_blonde_hair_dark': (cx: 95, alto: 12, largo: 156),
  'woman_bald_light': (cx: 95.5, alto: 28, largo: 129),
  'woman_bald_medium_light': (cx: 95.5, alto: 28, largo: 129),
  'woman_bald_medium': (cx: 95.5, alto: 28, largo: 129),
  'woman_bald_medium_dark': (cx: 95.5, alto: 28, largo: 129),
  'woman_bald_dark': (cx: 95.5, alto: 28, largo: 129),
  'person_light': (cx: 96, alto: 13, largo: 144),
  'person_medium_light': (cx: 96, alto: 13, largo: 144),
  'person_medium': (cx: 96, alto: 13, largo: 144),
  'person_medium_dark': (cx: 96, alto: 13, largo: 144),
  'person_dark': (cx: 96, alto: 13, largo: 144),
  'person_beard_light': (cx: 96, alto: 12, largo: 144),
  'person_beard_medium_light': (cx: 96, alto: 12, largo: 144),
  'person_beard_medium': (cx: 96, alto: 12, largo: 144),
  'person_beard_medium_dark': (cx: 96, alto: 12, largo: 144),
  'person_beard_dark': (cx: 96, alto: 12, largo: 144),
  'person_curly_hair_light': (cx: 94, alto: 8, largo: 168),
  'person_curly_hair_medium_light': (cx: 94, alto: 8, largo: 168),
  'person_curly_hair_medium': (cx: 94, alto: 8, largo: 168),
  'person_curly_hair_medium_dark': (cx: 94, alto: 8, largo: 168),
  'person_curly_hair_dark': (cx: 94, alto: 8, largo: 168),
  'person_red_hair_light': (cx: 96, alto: 13, largo: 144),
  'person_red_hair_medium_light': (cx: 96, alto: 13, largo: 144),
  'person_red_hair_medium': (cx: 96, alto: 13, largo: 144),
  'person_red_hair_medium_dark': (cx: 96, alto: 13, largo: 144),
  'person_red_hair_dark': (cx: 96, alto: 13, largo: 144),
  'person_white_hair_light': (cx: 96, alto: 13, largo: 144),
  'person_white_hair_medium_light': (cx: 96, alto: 13, largo: 144),
  'person_white_hair_medium': (cx: 96, alto: 13, largo: 144),
  'person_white_hair_medium_dark': (cx: 96, alto: 13, largo: 144),
  'person_white_hair_dark': (cx: 96, alto: 13, largo: 144),
  'person_blonde_hair_light': (cx: 96, alto: 13, largo: 144),
  'person_blonde_hair_medium_light': (cx: 96, alto: 13, largo: 144),
  'person_blonde_hair_medium': (cx: 96, alto: 13, largo: 144),
  'person_blonde_hair_medium_dark': (cx: 96, alto: 13, largo: 144),
  'person_blonde_hair_dark': (cx: 96, alto: 13, largo: 144),
  'person_bald_light': (cx: 95.5, alto: 24, largo: 129),
  'person_bald_medium_light': (cx: 95.5, alto: 24, largo: 129),
  'person_bald_medium': (cx: 95.5, alto: 24, largo: 129),
  'person_bald_medium_dark': (cx: 95.5, alto: 24, largo: 129),
  'person_bald_dark': (cx: 95.5, alto: 24, largo: 129),
  'boy_light': (cx: 100, alto: 12, largo: 144),
  'boy_medium_light': (cx: 100, alto: 12, largo: 144),
  'boy_medium': (cx: 100, alto: 12, largo: 144),
  'boy_medium_dark': (cx: 100, alto: 12, largo: 144),
  'boy_dark': (cx: 100, alto: 12, largo: 144),
  'girl_light': (cx: 95.5, alto: 12, largo: 143),
  'girl_medium_light': (cx: 95.5, alto: 12, largo: 143),
  'girl_medium': (cx: 95.5, alto: 12, largo: 143),
  'girl_medium_dark': (cx: 95.5, alto: 12, largo: 143),
  'girl_dark': (cx: 95.5, alto: 12, largo: 143),
  'old_man_light': (cx: 95.5, alto: 27, largo: 135),
  'old_man_medium_light': (cx: 95.5, alto: 27, largo: 135),
  'old_man_medium': (cx: 95.5, alto: 27, largo: 135),
  'old_man_medium_dark': (cx: 95.5, alto: 27, largo: 135),
  'old_man_dark': (cx: 95.5, alto: 27, largo: 135),
  'old_woman_light': (cx: 95.5, alto: 12, largo: 131),
  'old_woman_medium_light': (cx: 95.5, alto: 12, largo: 131),
  'old_woman_medium': (cx: 95.5, alto: 12, largo: 131),
  'old_woman_medium_dark': (cx: 95.5, alto: 12, largo: 131),
  'old_woman_dark': (cx: 95.5, alto: 12, largo: 131),
  'man_office_worker_light': (cx: 95.5, alto: 12, largo: 77),
  'man_office_worker_medium_light': (cx: 95.5, alto: 12, largo: 77),
  'man_office_worker_medium': (cx: 95.5, alto: 12, largo: 77),
  'man_office_worker_medium_dark': (cx: 95.5, alto: 12, largo: 77),
  'man_office_worker_dark': (cx: 95.5, alto: 12, largo: 77),
  'woman_office_worker_light': (cx: 95.5, alto: 14, largo: 91),
  'woman_office_worker_medium_light': (cx: 95.5, alto: 14, largo: 91),
  'woman_office_worker_medium': (cx: 95.5, alto: 14, largo: 91),
  'woman_office_worker_medium_dark': (cx: 95.5, alto: 14, largo: 91),
  'woman_office_worker_dark': (cx: 95.5, alto: 14, largo: 91),
  'man_health_worker_light': (cx: 95.5, alto: 12, largo: 77),
  'man_health_worker_medium_light': (cx: 95.5, alto: 12, largo: 77),
  'man_health_worker_medium': (cx: 95.5, alto: 12, largo: 77),
  'man_health_worker_medium_dark': (cx: 95.5, alto: 12, largo: 77),
  'man_health_worker_dark': (cx: 95.5, alto: 12, largo: 77),
  'woman_health_worker_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_health_worker_medium_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_health_worker_medium': (cx: 95.5, alto: 12, largo: 91),
  'woman_health_worker_medium_dark': (cx: 95.5, alto: 12, largo: 91),
  'woman_health_worker_dark': (cx: 95.5, alto: 12, largo: 91),
  'man_cook_light': (cx: 96, alto: 12, largo: 88),
  'man_cook_medium_light': (cx: 96, alto: 12, largo: 88),
  'man_cook_medium': (cx: 96, alto: 12, largo: 88),
  'man_cook_medium_dark': (cx: 96, alto: 12, largo: 88),
  'man_cook_dark': (cx: 96, alto: 12, largo: 88),
  'woman_cook_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_cook_medium_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_cook_medium': (cx: 95.5, alto: 12, largo: 91),
  'woman_cook_medium_dark': (cx: 95.5, alto: 12, largo: 91),
  'woman_cook_dark': (cx: 95.5, alto: 12, largo: 91),
  'man_in_tuxedo_light': (cx: 95.5, alto: 12, largo: 77),
  'man_in_tuxedo_medium_light': (cx: 95.5, alto: 12, largo: 77),
  'man_in_tuxedo_medium': (cx: 95.5, alto: 12, largo: 77),
  'man_in_tuxedo_medium_dark': (cx: 95.5, alto: 12, largo: 77),
  'man_in_tuxedo_dark': (cx: 95.5, alto: 12, largo: 77),
  'woman_in_tuxedo_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_in_tuxedo_medium_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_in_tuxedo_medium': (cx: 95.5, alto: 12, largo: 91),
  'woman_in_tuxedo_medium_dark': (cx: 95.5, alto: 12, largo: 91),
  'woman_in_tuxedo_dark': (cx: 95.5, alto: 12, largo: 91),
  'man_with_veil_light': (cx: 95.5, alto: 12, largo: 129),
  'man_with_veil_medium_light': (cx: 95.5, alto: 12, largo: 129),
  'man_with_veil_medium': (cx: 95.5, alto: 12, largo: 129),
  'man_with_veil_medium_dark': (cx: 95.5, alto: 12, largo: 129),
  'man_with_veil_dark': (cx: 95.5, alto: 12, largo: 129),
  'woman_with_veil_light': (cx: 95.5, alto: 12, largo: 129),
  'woman_with_veil_medium_light': (cx: 95.5, alto: 12, largo: 129),
  'woman_with_veil_medium': (cx: 95.5, alto: 12, largo: 129),
  'woman_with_veil_medium_dark': (cx: 95.5, alto: 12, largo: 129),
  'woman_with_veil_dark': (cx: 95.5, alto: 12, largo: 129),
  'man_firefighter_light': (cx: 95.5, alto: 12, largo: 103),
  'man_firefighter_medium_light': (cx: 95.5, alto: 12, largo: 103),
  'man_firefighter_medium': (cx: 95.5, alto: 12, largo: 103),
  'man_firefighter_medium_dark': (cx: 95.5, alto: 12, largo: 103),
  'man_firefighter_dark': (cx: 95.5, alto: 12, largo: 103),
  'woman_firefighter_light': (cx: 95.5, alto: 12, largo: 103),
  'woman_firefighter_medium_light': (cx: 95.5, alto: 12, largo: 103),
  'woman_firefighter_medium': (cx: 95.5, alto: 12, largo: 103),
  'woman_firefighter_medium_dark': (cx: 95.5, alto: 12, largo: 103),
  'woman_firefighter_dark': (cx: 95.5, alto: 12, largo: 103),
  'man_police_officer_light': (cx: 95.5, alto: 12, largo: 99),
  'man_police_officer_medium_light': (cx: 95.5, alto: 12, largo: 99),
  'man_police_officer_medium': (cx: 95.5, alto: 12, largo: 99),
  'man_police_officer_medium_dark': (cx: 95.5, alto: 12, largo: 99),
  'man_police_officer_dark': (cx: 95.5, alto: 12, largo: 99),
  'woman_police_officer_light': (cx: 95.5, alto: 12, largo: 103),
  'woman_police_officer_medium_light': (cx: 95.5, alto: 12, largo: 103),
  'woman_police_officer_medium': (cx: 95.5, alto: 12, largo: 103),
  'woman_police_officer_medium_dark': (cx: 95.5, alto: 12, largo: 103),
  'woman_police_officer_dark': (cx: 95.5, alto: 12, largo: 103),
  'man_construction_worker_light': (cx: 95.5, alto: 12, largo: 89),
  'man_construction_worker_medium_light': (cx: 95.5, alto: 12, largo: 89),
  'man_construction_worker_medium': (cx: 95.5, alto: 12, largo: 89),
  'man_construction_worker_medium_dark': (cx: 95.5, alto: 12, largo: 89),
  'man_construction_worker_dark': (cx: 95.5, alto: 12, largo: 89),
  'woman_construction_worker_light': (cx: 95.5, alto: 12, largo: 101),
  'woman_construction_worker_medium_light': (cx: 95.5, alto: 12, largo: 101),
  'woman_construction_worker_medium': (cx: 95.5, alto: 12, largo: 101),
  'woman_construction_worker_medium_dark': (cx: 95.5, alto: 12, largo: 101),
  'woman_construction_worker_dark': (cx: 95.5, alto: 12, largo: 101),
  'man_factory_worker_light': (cx: 103, alto: 12, largo: 132),
  'man_factory_worker_medium_light': (cx: 103, alto: 12, largo: 132),
  'man_factory_worker_medium': (cx: 103, alto: 12, largo: 132),
  'man_factory_worker_medium_dark': (cx: 103, alto: 12, largo: 132),
  'man_factory_worker_dark': (cx: 103, alto: 12, largo: 132),
  'woman_factory_worker_light': (cx: 103, alto: 12, largo: 132),
  'woman_factory_worker_medium_light': (cx: 103, alto: 12, largo: 132),
  'woman_factory_worker_medium': (cx: 103, alto: 12, largo: 132),
  'woman_factory_worker_medium_dark': (cx: 103, alto: 12, largo: 132),
  'woman_factory_worker_dark': (cx: 103, alto: 12, largo: 132),
  'man_mechanic_light': (cx: 92.5, alto: 12, largo: 77),
  'man_mechanic_medium_light': (cx: 92.5, alto: 12, largo: 77),
  'man_mechanic_medium': (cx: 92.5, alto: 12, largo: 77),
  'man_mechanic_medium_dark': (cx: 92.5, alto: 12, largo: 77),
  'man_mechanic_dark': (cx: 92.5, alto: 12, largo: 77),
  'woman_mechanic_light': (cx: 92.5, alto: 12, largo: 89),
  'woman_mechanic_medium_light': (cx: 92.5, alto: 12, largo: 89),
  'woman_mechanic_medium': (cx: 92.5, alto: 12, largo: 89),
  'woman_mechanic_medium_dark': (cx: 92.5, alto: 12, largo: 89),
  'woman_mechanic_dark': (cx: 92.5, alto: 12, largo: 89),
  'man_farmer_light': (cx: 105, alto: 12, largo: 140),
  'man_farmer_medium_light': (cx: 105, alto: 12, largo: 140),
  'man_farmer_medium': (cx: 105, alto: 12, largo: 140),
  'man_farmer_medium_dark': (cx: 105, alto: 12, largo: 140),
  'man_farmer_dark': (cx: 105, alto: 12, largo: 140),
  'woman_farmer_light': (cx: 105, alto: 12, largo: 140),
  'woman_farmer_medium_light': (cx: 105, alto: 12, largo: 140),
  'woman_farmer_medium': (cx: 105, alto: 12, largo: 140),
  'woman_farmer_medium_dark': (cx: 105, alto: 12, largo: 140),
  'woman_farmer_dark': (cx: 105, alto: 12, largo: 140),
  'man_pilot_light': (cx: 95.5, alto: 12, largo: 79),
  'man_pilot_medium_light': (cx: 95.5, alto: 12, largo: 79),
  'man_pilot_medium': (cx: 95.5, alto: 12, largo: 79),
  'man_pilot_medium_dark': (cx: 95.5, alto: 12, largo: 79),
  'man_pilot_dark': (cx: 95.5, alto: 12, largo: 79),
  'woman_pilot_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_pilot_medium_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_pilot_medium': (cx: 95.5, alto: 12, largo: 91),
  'woman_pilot_medium_dark': (cx: 95.5, alto: 12, largo: 91),
  'woman_pilot_dark': (cx: 95.5, alto: 12, largo: 91),
  'man_astronaut_light': (cx: 95.5, alto: 12, largo: 119),
  'man_astronaut_medium_light': (cx: 95.5, alto: 12, largo: 119),
  'man_astronaut_medium': (cx: 95.5, alto: 12, largo: 119),
  'man_astronaut_medium_dark': (cx: 95.5, alto: 12, largo: 119),
  'man_astronaut_dark': (cx: 95.5, alto: 12, largo: 119),
  'woman_astronaut_light': (cx: 95.5, alto: 12, largo: 119),
  'woman_astronaut_medium_light': (cx: 95.5, alto: 12, largo: 119),
  'woman_astronaut_medium': (cx: 95.5, alto: 12, largo: 119),
  'woman_astronaut_medium_dark': (cx: 95.5, alto: 12, largo: 119),
  'woman_astronaut_dark': (cx: 95.5, alto: 12, largo: 119),
  'man_judge_light': (cx: 95.5, alto: 12, largo: 77),
  'man_judge_medium_light': (cx: 95.5, alto: 12, largo: 77),
  'man_judge_medium': (cx: 95.5, alto: 12, largo: 77),
  'man_judge_medium_dark': (cx: 95.5, alto: 12, largo: 77),
  'man_judge_dark': (cx: 95.5, alto: 12, largo: 77),
  'woman_judge_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_judge_medium_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_judge_medium': (cx: 95.5, alto: 12, largo: 91),
  'woman_judge_medium_dark': (cx: 95.5, alto: 12, largo: 91),
  'woman_judge_dark': (cx: 95.5, alto: 12, largo: 91),
  'man_superhero_light': (cx: 95.5, alto: 12, largo: 77),
  'man_superhero_medium_light': (cx: 95.5, alto: 12, largo: 77),
  'man_superhero_medium': (cx: 95.5, alto: 12, largo: 77),
  'man_superhero_medium_dark': (cx: 95.5, alto: 12, largo: 77),
  'man_superhero_dark': (cx: 95.5, alto: 12, largo: 77),
  'woman_superhero_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_superhero_medium_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_superhero_medium': (cx: 95.5, alto: 12, largo: 91),
  'woman_superhero_medium_dark': (cx: 95.5, alto: 12, largo: 91),
  'woman_superhero_dark': (cx: 95.5, alto: 12, largo: 91),
  'man_scientist_light': (cx: 92.5, alto: 12, largo: 77),
  'man_scientist_medium_light': (cx: 92.5, alto: 12, largo: 77),
  'man_scientist_medium': (cx: 92.5, alto: 12, largo: 77),
  'man_scientist_medium_dark': (cx: 92.5, alto: 12, largo: 77),
  'man_scientist_dark': (cx: 92.5, alto: 12, largo: 77),
  'woman_scientist_light': (cx: 92.5, alto: 12, largo: 91),
  'woman_scientist_medium_light': (cx: 92.5, alto: 12, largo: 91),
  'woman_scientist_medium': (cx: 92.5, alto: 12, largo: 91),
  'woman_scientist_medium_dark': (cx: 92.5, alto: 12, largo: 91),
  'woman_scientist_dark': (cx: 92.5, alto: 12, largo: 91),
  'man_teacher_light': (cx: 95.5, alto: 12, largo: 169),
  'man_teacher_medium_light': (cx: 95.5, alto: 12, largo: 169),
  'man_teacher_medium': (cx: 95.5, alto: 12, largo: 169),
  'man_teacher_medium_dark': (cx: 95.5, alto: 12, largo: 169),
  'man_teacher_dark': (cx: 95.5, alto: 12, largo: 169),
  'woman_teacher_light': (cx: 95.5, alto: 12, largo: 169),
  'woman_teacher_medium_light': (cx: 95.5, alto: 12, largo: 169),
  'woman_teacher_medium': (cx: 95.5, alto: 12, largo: 169),
  'woman_teacher_medium_dark': (cx: 95.5, alto: 12, largo: 169),
  'woman_teacher_dark': (cx: 95.5, alto: 12, largo: 169),
  'man_student_light': (cx: 97.5, alto: 12, largo: 111),
  'man_student_medium_light': (cx: 97.5, alto: 12, largo: 111),
  'man_student_medium': (cx: 97.5, alto: 12, largo: 111),
  'man_student_medium_dark': (cx: 97.5, alto: 12, largo: 111),
  'man_student_dark': (cx: 97.5, alto: 12, largo: 111),
  'woman_student_light': (cx: 97.5, alto: 12, largo: 111),
  'woman_student_medium_light': (cx: 97.5, alto: 12, largo: 111),
  'woman_student_medium': (cx: 97.5, alto: 12, largo: 111),
  'woman_student_medium_dark': (cx: 97.5, alto: 12, largo: 111),
  'woman_student_dark': (cx: 97.5, alto: 12, largo: 111),
  'man_technologist_light': (cx: 95.5, alto: 12, largo: 77),
  'man_technologist_medium_light': (cx: 95.5, alto: 12, largo: 77),
  'man_technologist_medium': (cx: 95.5, alto: 12, largo: 77),
  'man_technologist_medium_dark': (cx: 95.5, alto: 12, largo: 77),
  'man_technologist_dark': (cx: 95.5, alto: 12, largo: 77),
  'woman_technologist_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_technologist_medium_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_technologist_medium': (cx: 95.5, alto: 12, largo: 91),
  'woman_technologist_medium_dark': (cx: 95.5, alto: 12, largo: 91),
  'woman_technologist_dark': (cx: 95.5, alto: 12, largo: 91),
  'man_artist_light': (cx: 93, alto: 12, largo: 84),
  'man_artist_medium_light': (cx: 93, alto: 12, largo: 84),
  'man_artist_medium': (cx: 93, alto: 12, largo: 84),
  'man_artist_medium_dark': (cx: 93, alto: 12, largo: 84),
  'man_artist_dark': (cx: 93, alto: 12, largo: 84),
  'woman_artist_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_artist_medium_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_artist_medium': (cx: 95.5, alto: 12, largo: 91),
  'woman_artist_medium_dark': (cx: 95.5, alto: 12, largo: 91),
  'woman_artist_dark': (cx: 95.5, alto: 12, largo: 91),
  'man_singer_light': (cx: 90.5, alto: 19, largo: 79),
  'man_singer_medium_light': (cx: 90.5, alto: 19, largo: 79),
  'man_singer_medium': (cx: 90.5, alto: 19, largo: 79),
  'man_singer_medium_dark': (cx: 90.5, alto: 19, largo: 79),
  'man_singer_dark': (cx: 90.5, alto: 19, largo: 79),
  'woman_singer_light': (cx: 90.5, alto: 19, largo: 93),
  'woman_singer_medium_light': (cx: 90.5, alto: 19, largo: 93),
  'woman_singer_medium': (cx: 90.5, alto: 19, largo: 93),
  'woman_singer_medium_dark': (cx: 90.5, alto: 19, largo: 93),
  'woman_singer_dark': (cx: 90.5, alto: 19, largo: 93),
  'man_guard_light': (cx: 95.5, alto: 12, largo: 81),
  'man_guard_medium_light': (cx: 95.5, alto: 12, largo: 81),
  'man_guard_medium': (cx: 95.5, alto: 12, largo: 81),
  'man_guard_medium_dark': (cx: 95.5, alto: 12, largo: 81),
  'man_guard_dark': (cx: 95.5, alto: 12, largo: 81),
  'woman_guard_light': (cx: 95.5, alto: 12, largo: 89),
  'woman_guard_medium_light': (cx: 95.5, alto: 12, largo: 89),
  'woman_guard_medium': (cx: 95.5, alto: 12, largo: 89),
  'woman_guard_medium_dark': (cx: 95.5, alto: 12, largo: 89),
  'woman_guard_dark': (cx: 95.5, alto: 12, largo: 89),
  'man_detective_light': (cx: 100, alto: 12, largo: 140),
  'man_detective_medium_light': (cx: 100, alto: 12, largo: 140),
  'man_detective_medium': (cx: 100, alto: 12, largo: 140),
  'man_detective_medium_dark': (cx: 100, alto: 12, largo: 140),
  'man_detective_dark': (cx: 100, alto: 12, largo: 140),
  'woman_detective_light': (cx: 100, alto: 12, largo: 140),
  'woman_detective_medium_light': (cx: 100, alto: 12, largo: 140),
  'woman_detective_medium': (cx: 100, alto: 12, largo: 140),
  'woman_detective_medium_dark': (cx: 100, alto: 12, largo: 140),
  'woman_detective_dark': (cx: 100, alto: 12, largo: 140),
  'man_wearing_turban_light': (cx: 96.5, alto: 11, largo: 141),
  'man_wearing_turban_medium_light': (cx: 96.5, alto: 11, largo: 141),
  'man_wearing_turban_medium': (cx: 96.5, alto: 11, largo: 141),
  'man_wearing_turban_medium_dark': (cx: 96.5, alto: 11, largo: 141),
  'man_wearing_turban_dark': (cx: 96.5, alto: 11, largo: 141),
  'woman_wearing_turban_light': (cx: 96.5, alto: 11, largo: 141),
  'woman_wearing_turban_medium_light': (cx: 96.5, alto: 11, largo: 141),
  'woman_wearing_turban_medium': (cx: 96.5, alto: 11, largo: 141),
  'woman_wearing_turban_medium_dark': (cx: 96.5, alto: 11, largo: 141),
  'woman_wearing_turban_dark': (cx: 96.5, alto: 11, largo: 141),
  'man_supervillain_light': (cx: 96, alto: 12, largo: 90),
  'man_supervillain_medium_light': (cx: 96, alto: 12, largo: 90),
  'man_supervillain_medium': (cx: 96, alto: 12, largo: 90),
  'man_supervillain_medium_dark': (cx: 96, alto: 12, largo: 90),
  'man_supervillain_dark': (cx: 96, alto: 12, largo: 90),
  'woman_supervillain_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_supervillain_medium_light': (cx: 95.5, alto: 12, largo: 91),
  'woman_supervillain_medium': (cx: 95.5, alto: 12, largo: 91),
  'woman_supervillain_medium_dark': (cx: 95.5, alto: 12, largo: 91),
  'woman_supervillain_dark': (cx: 95.5, alto: 12, largo: 91),
  'man_mage_light': (cx: 98, alto: 12, largo: 148),
  'man_mage_medium_light': (cx: 98, alto: 12, largo: 148),
  'man_mage_medium': (cx: 98, alto: 12, largo: 148),
  'man_mage_medium_dark': (cx: 98, alto: 12, largo: 148),
  'man_mage_dark': (cx: 98, alto: 12, largo: 148),
  'woman_mage_light': (cx: 98, alto: 12, largo: 148),
  'woman_mage_medium_light': (cx: 98, alto: 12, largo: 148),
  'woman_mage_medium': (cx: 98, alto: 12, largo: 148),
  'woman_mage_medium_dark': (cx: 98, alto: 12, largo: 148),
  'woman_mage_dark': (cx: 98, alto: 12, largo: 148),
  'man_fairy_light': (cx: 97, alto: 13, largo: 108),
  'man_fairy_medium_light': (cx: 97, alto: 13, largo: 108),
  'man_fairy_medium': (cx: 97, alto: 13, largo: 108),
  'man_fairy_medium_dark': (cx: 97, alto: 13, largo: 108),
  'man_fairy_dark': (cx: 97, alto: 13, largo: 108),
  'woman_fairy_light': (cx: 97, alto: 13, largo: 108),
  'woman_fairy_medium_light': (cx: 97, alto: 13, largo: 108),
  'woman_fairy_medium': (cx: 97, alto: 13, largo: 108),
  'woman_fairy_medium_dark': (cx: 97, alto: 13, largo: 108),
  'woman_fairy_dark': (cx: 97, alto: 13, largo: 108),
  'man_vampire_light': (cx: 96, alto: 12, largo: 130),
  'man_vampire_medium_light': (cx: 96, alto: 12, largo: 130),
  'man_vampire_medium': (cx: 96, alto: 12, largo: 130),
  'man_vampire_medium_dark': (cx: 96, alto: 12, largo: 130),
  'man_vampire_dark': (cx: 96, alto: 12, largo: 130),
  'woman_vampire_light': (cx: 96, alto: 13, largo: 130),
  'woman_vampire_medium_light': (cx: 96, alto: 13, largo: 130),
  'woman_vampire_medium': (cx: 96, alto: 13, largo: 130),
  'woman_vampire_medium_dark': (cx: 96, alto: 13, largo: 130),
  'woman_vampire_dark': (cx: 96, alto: 13, largo: 130),
  'man_elf_light': (cx: 96, alto: 13, largo: 110),
  'man_elf_medium_light': (cx: 96, alto: 13, largo: 110),
  'man_elf_medium': (cx: 96, alto: 13, largo: 110),
  'man_elf_medium_dark': (cx: 96, alto: 13, largo: 110),
  'man_elf_dark': (cx: 96, alto: 13, largo: 110),
  'woman_elf_light': (cx: 95.5, alto: 12, largo: 99),
  'woman_elf_medium_light': (cx: 95.5, alto: 12, largo: 99),
  'woman_elf_medium': (cx: 95.5, alto: 12, largo: 99),
  'woman_elf_medium_dark': (cx: 95.5, alto: 12, largo: 99),
  'woman_elf_dark': (cx: 95.5, alto: 12, largo: 99),
  'man_tipping_hand_light': (cx: 72.1, alto: 11, largo: 97.7),
  'man_tipping_hand_medium_light': (cx: 72, alto: 11, largo: 97.2),
  'man_tipping_hand_medium': (cx: 72.1, alto: 11, largo: 97.4),
  'man_tipping_hand_medium_dark': (cx: 72.1, alto: 11, largo: 97.6),
  'man_tipping_hand_dark': (cx: 72, alto: 11, largo: 97.1),
  'woman_tipping_hand_light': (cx: 72.2, alto: 4, largo: 121.6),
  'woman_tipping_hand_medium_light': (cx: 72.2, alto: 5, largo: 120.2),
  'woman_tipping_hand_medium': (cx: 72.4, alto: 6, largo: 119.3),
  'woman_tipping_hand_medium_dark': (cx: 72.2, alto: 4, largo: 121.9),
  'woman_tipping_hand_dark': (cx: 72.1, alto: 5, largo: 120.3),
  'man_raising_hand_light': (cx: 116.4, alto: 25, largo: 88.7),
  'man_raising_hand_medium_light': (cx: 116.5, alto: 25, largo: 88.7),
  'man_raising_hand_medium': (cx: 116.3, alto: 25, largo: 88.8),
  'man_raising_hand_medium_dark': (cx: 116.5, alto: 25, largo: 88.5),
  'man_raising_hand_dark': (cx: 116.4, alto: 25, largo: 88.9),
  'woman_raising_hand_light': (cx: 116.4, alto: 15, largo: 115.8),
  'woman_raising_hand_medium_light': (cx: 116.4, alto: 15, largo: 115.2),
  'woman_raising_hand_medium': (cx: 116.4, alto: 15, largo: 115.4),
  'woman_raising_hand_medium_dark': (cx: 116.4, alto: 15, largo: 115.6),
  'woman_raising_hand_dark': (cx: 116.3, alto: 16, largo: 115.1),
  'pregnant_woman_light': (cx: 107.5, alto: 12, largo: 79),
  'pregnant_woman_medium_light': (cx: 107.5, alto: 12, largo: 79),
  'pregnant_woman_medium': (cx: 107.5, alto: 12, largo: 79),
  'pregnant_woman_medium_dark': (cx: 107.5, alto: 12, largo: 79),
  'pregnant_woman_dark': (cx: 107.5, alto: 12, largo: 79),
};

/// «persona|capelli|carnagione» → il file della testa.
const testeDeiRitratti = <String, String>{
  'uomo|lisci|chiara': 'man_light',
  'uomo|lisci|chiara2': 'man_medium_light',
  'uomo|lisci|media': 'man_medium',
  'uomo|lisci|ambrata': 'man_medium_dark',
  'uomo|lisci|scura': 'man_dark',
  'uomo|barba|chiara': 'man_beard_light',
  'uomo|barba|chiara2': 'man_beard_medium_light',
  'uomo|barba|media': 'man_beard_medium',
  'uomo|barba|ambrata': 'man_beard_medium_dark',
  'uomo|barba|scura': 'man_beard_dark',
  'uomo|ricci|chiara': 'man_curly_hair_light',
  'uomo|ricci|chiara2': 'man_curly_hair_medium_light',
  'uomo|ricci|media': 'man_curly_hair_medium',
  'uomo|ricci|ambrata': 'man_curly_hair_medium_dark',
  'uomo|ricci|scura': 'man_curly_hair_dark',
  'uomo|rossi|chiara': 'man_red_hair_light',
  'uomo|rossi|chiara2': 'man_red_hair_medium_light',
  'uomo|rossi|media': 'man_red_hair_medium',
  'uomo|rossi|ambrata': 'man_red_hair_medium_dark',
  'uomo|rossi|scura': 'man_red_hair_dark',
  'uomo|bianchi|chiara': 'man_white_hair_light',
  'uomo|bianchi|chiara2': 'man_white_hair_medium_light',
  'uomo|bianchi|media': 'man_white_hair_medium',
  'uomo|bianchi|ambrata': 'man_white_hair_medium_dark',
  'uomo|bianchi|scura': 'man_white_hair_dark',
  'uomo|biondi|chiara': 'man_blonde_hair_light',
  'uomo|biondi|chiara2': 'man_blonde_hair_medium_light',
  'uomo|biondi|media': 'man_blonde_hair_medium',
  'uomo|biondi|ambrata': 'man_blonde_hair_medium_dark',
  'uomo|biondi|scura': 'man_blonde_hair_dark',
  'uomo|calvo|chiara': 'man_bald_light',
  'uomo|calvo|chiara2': 'man_bald_medium_light',
  'uomo|calvo|media': 'man_bald_medium',
  'uomo|calvo|ambrata': 'man_bald_medium_dark',
  'uomo|calvo|scura': 'man_bald_dark',
  'donna|lisci|chiara': 'woman_light',
  'donna|lisci|chiara2': 'woman_medium_light',
  'donna|lisci|media': 'woman_medium',
  'donna|lisci|ambrata': 'woman_medium_dark',
  'donna|lisci|scura': 'woman_dark',
  'donna|barba|chiara': 'woman_beard_light',
  'donna|barba|chiara2': 'woman_beard_medium_light',
  'donna|barba|media': 'woman_beard_medium',
  'donna|barba|ambrata': 'woman_beard_medium_dark',
  'donna|barba|scura': 'woman_beard_dark',
  'donna|ricci|chiara': 'woman_curly_hair_light',
  'donna|ricci|chiara2': 'woman_curly_hair_medium_light',
  'donna|ricci|media': 'woman_curly_hair_medium',
  'donna|ricci|ambrata': 'woman_curly_hair_medium_dark',
  'donna|ricci|scura': 'woman_curly_hair_dark',
  'donna|rossi|chiara': 'woman_red_hair_light',
  'donna|rossi|chiara2': 'woman_red_hair_medium_light',
  'donna|rossi|media': 'woman_red_hair_medium',
  'donna|rossi|ambrata': 'woman_red_hair_medium_dark',
  'donna|rossi|scura': 'woman_red_hair_dark',
  'donna|bianchi|chiara': 'woman_white_hair_light',
  'donna|bianchi|chiara2': 'woman_white_hair_medium_light',
  'donna|bianchi|media': 'woman_white_hair_medium',
  'donna|bianchi|ambrata': 'woman_white_hair_medium_dark',
  'donna|bianchi|scura': 'woman_white_hair_dark',
  'donna|biondi|chiara': 'woman_blonde_hair_light',
  'donna|biondi|chiara2': 'woman_blonde_hair_medium_light',
  'donna|biondi|media': 'woman_blonde_hair_medium',
  'donna|biondi|ambrata': 'woman_blonde_hair_medium_dark',
  'donna|biondi|scura': 'woman_blonde_hair_dark',
  'donna|calvo|chiara': 'woman_bald_light',
  'donna|calvo|chiara2': 'woman_bald_medium_light',
  'donna|calvo|media': 'woman_bald_medium',
  'donna|calvo|ambrata': 'woman_bald_medium_dark',
  'donna|calvo|scura': 'woman_bald_dark',
  'neutro|lisci|chiara': 'person_light',
  'neutro|lisci|chiara2': 'person_medium_light',
  'neutro|lisci|media': 'person_medium',
  'neutro|lisci|ambrata': 'person_medium_dark',
  'neutro|lisci|scura': 'person_dark',
  'neutro|barba|chiara': 'person_beard_light',
  'neutro|barba|chiara2': 'person_beard_medium_light',
  'neutro|barba|media': 'person_beard_medium',
  'neutro|barba|ambrata': 'person_beard_medium_dark',
  'neutro|barba|scura': 'person_beard_dark',
  'neutro|ricci|chiara': 'person_curly_hair_light',
  'neutro|ricci|chiara2': 'person_curly_hair_medium_light',
  'neutro|ricci|media': 'person_curly_hair_medium',
  'neutro|ricci|ambrata': 'person_curly_hair_medium_dark',
  'neutro|ricci|scura': 'person_curly_hair_dark',
  'neutro|rossi|chiara': 'person_red_hair_light',
  'neutro|rossi|chiara2': 'person_red_hair_medium_light',
  'neutro|rossi|media': 'person_red_hair_medium',
  'neutro|rossi|ambrata': 'person_red_hair_medium_dark',
  'neutro|rossi|scura': 'person_red_hair_dark',
  'neutro|bianchi|chiara': 'person_white_hair_light',
  'neutro|bianchi|chiara2': 'person_white_hair_medium_light',
  'neutro|bianchi|media': 'person_white_hair_medium',
  'neutro|bianchi|ambrata': 'person_white_hair_medium_dark',
  'neutro|bianchi|scura': 'person_white_hair_dark',
  'neutro|biondi|chiara': 'person_blonde_hair_light',
  'neutro|biondi|chiara2': 'person_blonde_hair_medium_light',
  'neutro|biondi|media': 'person_blonde_hair_medium',
  'neutro|biondi|ambrata': 'person_blonde_hair_medium_dark',
  'neutro|biondi|scura': 'person_blonde_hair_dark',
  'neutro|calvo|chiara': 'person_bald_light',
  'neutro|calvo|chiara2': 'person_bald_medium_light',
  'neutro|calvo|media': 'person_bald_medium',
  'neutro|calvo|ambrata': 'person_bald_medium_dark',
  'neutro|calvo|scura': 'person_bald_dark',
  'ragazzo||chiara': 'boy_light',
  'ragazzo||chiara2': 'boy_medium_light',
  'ragazzo||media': 'boy_medium',
  'ragazzo||ambrata': 'boy_medium_dark',
  'ragazzo||scura': 'boy_dark',
  'ragazza||chiara': 'girl_light',
  'ragazza||chiara2': 'girl_medium_light',
  'ragazza||media': 'girl_medium',
  'ragazza||ambrata': 'girl_medium_dark',
  'ragazza||scura': 'girl_dark',
  'anziano||chiara': 'old_man_light',
  'anziano||chiara2': 'old_man_medium_light',
  'anziano||media': 'old_man_medium',
  'anziano||ambrata': 'old_man_medium_dark',
  'anziano||scura': 'old_man_dark',
  'anziana||chiara': 'old_woman_light',
  'anziana||chiara2': 'old_woman_medium_light',
  'anziana||media': 'old_woman_medium',
  'anziana||ambrata': 'old_woman_medium_dark',
  'anziana||scura': 'old_woman_dark',
};

/// «vestito|genere|carnagione» → il file del busto.
const bustiDeiRitratti = <String, String>{
  'ufficio|uomo|chiara': 'man_office_worker_light',
  'ufficio|uomo|chiara2': 'man_office_worker_medium_light',
  'ufficio|uomo|media': 'man_office_worker_medium',
  'ufficio|uomo|ambrata': 'man_office_worker_medium_dark',
  'ufficio|uomo|scura': 'man_office_worker_dark',
  'ufficio|donna|chiara': 'woman_office_worker_light',
  'ufficio|donna|chiara2': 'woman_office_worker_medium_light',
  'ufficio|donna|media': 'woman_office_worker_medium',
  'ufficio|donna|ambrata': 'woman_office_worker_medium_dark',
  'ufficio|donna|scura': 'woman_office_worker_dark',
  'medico|uomo|chiara': 'man_health_worker_light',
  'medico|uomo|chiara2': 'man_health_worker_medium_light',
  'medico|uomo|media': 'man_health_worker_medium',
  'medico|uomo|ambrata': 'man_health_worker_medium_dark',
  'medico|uomo|scura': 'man_health_worker_dark',
  'medico|donna|chiara': 'woman_health_worker_light',
  'medico|donna|chiara2': 'woman_health_worker_medium_light',
  'medico|donna|media': 'woman_health_worker_medium',
  'medico|donna|ambrata': 'woman_health_worker_medium_dark',
  'medico|donna|scura': 'woman_health_worker_dark',
  'cuoco|uomo|chiara': 'man_cook_light',
  'cuoco|uomo|chiara2': 'man_cook_medium_light',
  'cuoco|uomo|media': 'man_cook_medium',
  'cuoco|uomo|ambrata': 'man_cook_medium_dark',
  'cuoco|uomo|scura': 'man_cook_dark',
  'cuoco|donna|chiara': 'woman_cook_light',
  'cuoco|donna|chiara2': 'woman_cook_medium_light',
  'cuoco|donna|media': 'woman_cook_medium',
  'cuoco|donna|ambrata': 'woman_cook_medium_dark',
  'cuoco|donna|scura': 'woman_cook_dark',
  'smoking|uomo|chiara': 'man_in_tuxedo_light',
  'smoking|uomo|chiara2': 'man_in_tuxedo_medium_light',
  'smoking|uomo|media': 'man_in_tuxedo_medium',
  'smoking|uomo|ambrata': 'man_in_tuxedo_medium_dark',
  'smoking|uomo|scura': 'man_in_tuxedo_dark',
  'smoking|donna|chiara': 'woman_in_tuxedo_light',
  'smoking|donna|chiara2': 'woman_in_tuxedo_medium_light',
  'smoking|donna|media': 'woman_in_tuxedo_medium',
  'smoking|donna|ambrata': 'woman_in_tuxedo_medium_dark',
  'smoking|donna|scura': 'woman_in_tuxedo_dark',
  'velo|uomo|chiara': 'man_with_veil_light',
  'velo|uomo|chiara2': 'man_with_veil_medium_light',
  'velo|uomo|media': 'man_with_veil_medium',
  'velo|uomo|ambrata': 'man_with_veil_medium_dark',
  'velo|uomo|scura': 'man_with_veil_dark',
  'velo|donna|chiara': 'woman_with_veil_light',
  'velo|donna|chiara2': 'woman_with_veil_medium_light',
  'velo|donna|media': 'woman_with_veil_medium',
  'velo|donna|ambrata': 'woman_with_veil_medium_dark',
  'velo|donna|scura': 'woman_with_veil_dark',
  'pompiere|uomo|chiara': 'man_firefighter_light',
  'pompiere|uomo|chiara2': 'man_firefighter_medium_light',
  'pompiere|uomo|media': 'man_firefighter_medium',
  'pompiere|uomo|ambrata': 'man_firefighter_medium_dark',
  'pompiere|uomo|scura': 'man_firefighter_dark',
  'pompiere|donna|chiara': 'woman_firefighter_light',
  'pompiere|donna|chiara2': 'woman_firefighter_medium_light',
  'pompiere|donna|media': 'woman_firefighter_medium',
  'pompiere|donna|ambrata': 'woman_firefighter_medium_dark',
  'pompiere|donna|scura': 'woman_firefighter_dark',
  'poliziotto|uomo|chiara': 'man_police_officer_light',
  'poliziotto|uomo|chiara2': 'man_police_officer_medium_light',
  'poliziotto|uomo|media': 'man_police_officer_medium',
  'poliziotto|uomo|ambrata': 'man_police_officer_medium_dark',
  'poliziotto|uomo|scura': 'man_police_officer_dark',
  'poliziotto|donna|chiara': 'woman_police_officer_light',
  'poliziotto|donna|chiara2': 'woman_police_officer_medium_light',
  'poliziotto|donna|media': 'woman_police_officer_medium',
  'poliziotto|donna|ambrata': 'woman_police_officer_medium_dark',
  'poliziotto|donna|scura': 'woman_police_officer_dark',
  'muratore|uomo|chiara': 'man_construction_worker_light',
  'muratore|uomo|chiara2': 'man_construction_worker_medium_light',
  'muratore|uomo|media': 'man_construction_worker_medium',
  'muratore|uomo|ambrata': 'man_construction_worker_medium_dark',
  'muratore|uomo|scura': 'man_construction_worker_dark',
  'muratore|donna|chiara': 'woman_construction_worker_light',
  'muratore|donna|chiara2': 'woman_construction_worker_medium_light',
  'muratore|donna|media': 'woman_construction_worker_medium',
  'muratore|donna|ambrata': 'woman_construction_worker_medium_dark',
  'muratore|donna|scura': 'woman_construction_worker_dark',
  'operaio|uomo|chiara': 'man_factory_worker_light',
  'operaio|uomo|chiara2': 'man_factory_worker_medium_light',
  'operaio|uomo|media': 'man_factory_worker_medium',
  'operaio|uomo|ambrata': 'man_factory_worker_medium_dark',
  'operaio|uomo|scura': 'man_factory_worker_dark',
  'operaio|donna|chiara': 'woman_factory_worker_light',
  'operaio|donna|chiara2': 'woman_factory_worker_medium_light',
  'operaio|donna|media': 'woman_factory_worker_medium',
  'operaio|donna|ambrata': 'woman_factory_worker_medium_dark',
  'operaio|donna|scura': 'woman_factory_worker_dark',
  'meccanico|uomo|chiara': 'man_mechanic_light',
  'meccanico|uomo|chiara2': 'man_mechanic_medium_light',
  'meccanico|uomo|media': 'man_mechanic_medium',
  'meccanico|uomo|ambrata': 'man_mechanic_medium_dark',
  'meccanico|uomo|scura': 'man_mechanic_dark',
  'meccanico|donna|chiara': 'woman_mechanic_light',
  'meccanico|donna|chiara2': 'woman_mechanic_medium_light',
  'meccanico|donna|media': 'woman_mechanic_medium',
  'meccanico|donna|ambrata': 'woman_mechanic_medium_dark',
  'meccanico|donna|scura': 'woman_mechanic_dark',
  'contadino|uomo|chiara': 'man_farmer_light',
  'contadino|uomo|chiara2': 'man_farmer_medium_light',
  'contadino|uomo|media': 'man_farmer_medium',
  'contadino|uomo|ambrata': 'man_farmer_medium_dark',
  'contadino|uomo|scura': 'man_farmer_dark',
  'contadino|donna|chiara': 'woman_farmer_light',
  'contadino|donna|chiara2': 'woman_farmer_medium_light',
  'contadino|donna|media': 'woman_farmer_medium',
  'contadino|donna|ambrata': 'woman_farmer_medium_dark',
  'contadino|donna|scura': 'woman_farmer_dark',
  'pilota|uomo|chiara': 'man_pilot_light',
  'pilota|uomo|chiara2': 'man_pilot_medium_light',
  'pilota|uomo|media': 'man_pilot_medium',
  'pilota|uomo|ambrata': 'man_pilot_medium_dark',
  'pilota|uomo|scura': 'man_pilot_dark',
  'pilota|donna|chiara': 'woman_pilot_light',
  'pilota|donna|chiara2': 'woman_pilot_medium_light',
  'pilota|donna|media': 'woman_pilot_medium',
  'pilota|donna|ambrata': 'woman_pilot_medium_dark',
  'pilota|donna|scura': 'woman_pilot_dark',
  'astronauta|uomo|chiara': 'man_astronaut_light',
  'astronauta|uomo|chiara2': 'man_astronaut_medium_light',
  'astronauta|uomo|media': 'man_astronaut_medium',
  'astronauta|uomo|ambrata': 'man_astronaut_medium_dark',
  'astronauta|uomo|scura': 'man_astronaut_dark',
  'astronauta|donna|chiara': 'woman_astronaut_light',
  'astronauta|donna|chiara2': 'woman_astronaut_medium_light',
  'astronauta|donna|media': 'woman_astronaut_medium',
  'astronauta|donna|ambrata': 'woman_astronaut_medium_dark',
  'astronauta|donna|scura': 'woman_astronaut_dark',
  'giudice|uomo|chiara': 'man_judge_light',
  'giudice|uomo|chiara2': 'man_judge_medium_light',
  'giudice|uomo|media': 'man_judge_medium',
  'giudice|uomo|ambrata': 'man_judge_medium_dark',
  'giudice|uomo|scura': 'man_judge_dark',
  'giudice|donna|chiara': 'woman_judge_light',
  'giudice|donna|chiara2': 'woman_judge_medium_light',
  'giudice|donna|media': 'woman_judge_medium',
  'giudice|donna|ambrata': 'woman_judge_medium_dark',
  'giudice|donna|scura': 'woman_judge_dark',
  'supereroe|uomo|chiara': 'man_superhero_light',
  'supereroe|uomo|chiara2': 'man_superhero_medium_light',
  'supereroe|uomo|media': 'man_superhero_medium',
  'supereroe|uomo|ambrata': 'man_superhero_medium_dark',
  'supereroe|uomo|scura': 'man_superhero_dark',
  'supereroe|donna|chiara': 'woman_superhero_light',
  'supereroe|donna|chiara2': 'woman_superhero_medium_light',
  'supereroe|donna|media': 'woman_superhero_medium',
  'supereroe|donna|ambrata': 'woman_superhero_medium_dark',
  'supereroe|donna|scura': 'woman_superhero_dark',
  'scienziato|uomo|chiara': 'man_scientist_light',
  'scienziato|uomo|chiara2': 'man_scientist_medium_light',
  'scienziato|uomo|media': 'man_scientist_medium',
  'scienziato|uomo|ambrata': 'man_scientist_medium_dark',
  'scienziato|uomo|scura': 'man_scientist_dark',
  'scienziato|donna|chiara': 'woman_scientist_light',
  'scienziato|donna|chiara2': 'woman_scientist_medium_light',
  'scienziato|donna|media': 'woman_scientist_medium',
  'scienziato|donna|ambrata': 'woman_scientist_medium_dark',
  'scienziato|donna|scura': 'woman_scientist_dark',
  'insegnante|uomo|chiara': 'man_teacher_light',
  'insegnante|uomo|chiara2': 'man_teacher_medium_light',
  'insegnante|uomo|media': 'man_teacher_medium',
  'insegnante|uomo|ambrata': 'man_teacher_medium_dark',
  'insegnante|uomo|scura': 'man_teacher_dark',
  'insegnante|donna|chiara': 'woman_teacher_light',
  'insegnante|donna|chiara2': 'woman_teacher_medium_light',
  'insegnante|donna|media': 'woman_teacher_medium',
  'insegnante|donna|ambrata': 'woman_teacher_medium_dark',
  'insegnante|donna|scura': 'woman_teacher_dark',
  'studente|uomo|chiara': 'man_student_light',
  'studente|uomo|chiara2': 'man_student_medium_light',
  'studente|uomo|media': 'man_student_medium',
  'studente|uomo|ambrata': 'man_student_medium_dark',
  'studente|uomo|scura': 'man_student_dark',
  'studente|donna|chiara': 'woman_student_light',
  'studente|donna|chiara2': 'woman_student_medium_light',
  'studente|donna|media': 'woman_student_medium',
  'studente|donna|ambrata': 'woman_student_medium_dark',
  'studente|donna|scura': 'woman_student_dark',
  'informatico|uomo|chiara': 'man_technologist_light',
  'informatico|uomo|chiara2': 'man_technologist_medium_light',
  'informatico|uomo|media': 'man_technologist_medium',
  'informatico|uomo|ambrata': 'man_technologist_medium_dark',
  'informatico|uomo|scura': 'man_technologist_dark',
  'informatico|donna|chiara': 'woman_technologist_light',
  'informatico|donna|chiara2': 'woman_technologist_medium_light',
  'informatico|donna|media': 'woman_technologist_medium',
  'informatico|donna|ambrata': 'woman_technologist_medium_dark',
  'informatico|donna|scura': 'woman_technologist_dark',
  'artista|uomo|chiara': 'man_artist_light',
  'artista|uomo|chiara2': 'man_artist_medium_light',
  'artista|uomo|media': 'man_artist_medium',
  'artista|uomo|ambrata': 'man_artist_medium_dark',
  'artista|uomo|scura': 'man_artist_dark',
  'artista|donna|chiara': 'woman_artist_light',
  'artista|donna|chiara2': 'woman_artist_medium_light',
  'artista|donna|media': 'woman_artist_medium',
  'artista|donna|ambrata': 'woman_artist_medium_dark',
  'artista|donna|scura': 'woman_artist_dark',
  'cantante|uomo|chiara': 'man_singer_light',
  'cantante|uomo|chiara2': 'man_singer_medium_light',
  'cantante|uomo|media': 'man_singer_medium',
  'cantante|uomo|ambrata': 'man_singer_medium_dark',
  'cantante|uomo|scura': 'man_singer_dark',
  'cantante|donna|chiara': 'woman_singer_light',
  'cantante|donna|chiara2': 'woman_singer_medium_light',
  'cantante|donna|media': 'woman_singer_medium',
  'cantante|donna|ambrata': 'woman_singer_medium_dark',
  'cantante|donna|scura': 'woman_singer_dark',
  'guardia|uomo|chiara': 'man_guard_light',
  'guardia|uomo|chiara2': 'man_guard_medium_light',
  'guardia|uomo|media': 'man_guard_medium',
  'guardia|uomo|ambrata': 'man_guard_medium_dark',
  'guardia|uomo|scura': 'man_guard_dark',
  'guardia|donna|chiara': 'woman_guard_light',
  'guardia|donna|chiara2': 'woman_guard_medium_light',
  'guardia|donna|media': 'woman_guard_medium',
  'guardia|donna|ambrata': 'woman_guard_medium_dark',
  'guardia|donna|scura': 'woman_guard_dark',
  'detective|uomo|chiara': 'man_detective_light',
  'detective|uomo|chiara2': 'man_detective_medium_light',
  'detective|uomo|media': 'man_detective_medium',
  'detective|uomo|ambrata': 'man_detective_medium_dark',
  'detective|uomo|scura': 'man_detective_dark',
  'detective|donna|chiara': 'woman_detective_light',
  'detective|donna|chiara2': 'woman_detective_medium_light',
  'detective|donna|media': 'woman_detective_medium',
  'detective|donna|ambrata': 'woman_detective_medium_dark',
  'detective|donna|scura': 'woman_detective_dark',
  'turbante|uomo|chiara': 'man_wearing_turban_light',
  'turbante|uomo|chiara2': 'man_wearing_turban_medium_light',
  'turbante|uomo|media': 'man_wearing_turban_medium',
  'turbante|uomo|ambrata': 'man_wearing_turban_medium_dark',
  'turbante|uomo|scura': 'man_wearing_turban_dark',
  'turbante|donna|chiara': 'woman_wearing_turban_light',
  'turbante|donna|chiara2': 'woman_wearing_turban_medium_light',
  'turbante|donna|media': 'woman_wearing_turban_medium',
  'turbante|donna|ambrata': 'woman_wearing_turban_medium_dark',
  'turbante|donna|scura': 'woman_wearing_turban_dark',
  'supercattivo|uomo|chiara': 'man_supervillain_light',
  'supercattivo|uomo|chiara2': 'man_supervillain_medium_light',
  'supercattivo|uomo|media': 'man_supervillain_medium',
  'supercattivo|uomo|ambrata': 'man_supervillain_medium_dark',
  'supercattivo|uomo|scura': 'man_supervillain_dark',
  'supercattivo|donna|chiara': 'woman_supervillain_light',
  'supercattivo|donna|chiara2': 'woman_supervillain_medium_light',
  'supercattivo|donna|media': 'woman_supervillain_medium',
  'supercattivo|donna|ambrata': 'woman_supervillain_medium_dark',
  'supercattivo|donna|scura': 'woman_supervillain_dark',
  'mago|uomo|chiara': 'man_mage_light',
  'mago|uomo|chiara2': 'man_mage_medium_light',
  'mago|uomo|media': 'man_mage_medium',
  'mago|uomo|ambrata': 'man_mage_medium_dark',
  'mago|uomo|scura': 'man_mage_dark',
  'mago|donna|chiara': 'woman_mage_light',
  'mago|donna|chiara2': 'woman_mage_medium_light',
  'mago|donna|media': 'woman_mage_medium',
  'mago|donna|ambrata': 'woman_mage_medium_dark',
  'mago|donna|scura': 'woman_mage_dark',
  'fata|uomo|chiara': 'man_fairy_light',
  'fata|uomo|chiara2': 'man_fairy_medium_light',
  'fata|uomo|media': 'man_fairy_medium',
  'fata|uomo|ambrata': 'man_fairy_medium_dark',
  'fata|uomo|scura': 'man_fairy_dark',
  'fata|donna|chiara': 'woman_fairy_light',
  'fata|donna|chiara2': 'woman_fairy_medium_light',
  'fata|donna|media': 'woman_fairy_medium',
  'fata|donna|ambrata': 'woman_fairy_medium_dark',
  'fata|donna|scura': 'woman_fairy_dark',
  'vampiro|uomo|chiara': 'man_vampire_light',
  'vampiro|uomo|chiara2': 'man_vampire_medium_light',
  'vampiro|uomo|media': 'man_vampire_medium',
  'vampiro|uomo|ambrata': 'man_vampire_medium_dark',
  'vampiro|uomo|scura': 'man_vampire_dark',
  'vampiro|donna|chiara': 'woman_vampire_light',
  'vampiro|donna|chiara2': 'woman_vampire_medium_light',
  'vampiro|donna|media': 'woman_vampire_medium',
  'vampiro|donna|ambrata': 'woman_vampire_medium_dark',
  'vampiro|donna|scura': 'woman_vampire_dark',
  'elfo|uomo|chiara': 'man_elf_light',
  'elfo|uomo|chiara2': 'man_elf_medium_light',
  'elfo|uomo|media': 'man_elf_medium',
  'elfo|uomo|ambrata': 'man_elf_medium_dark',
  'elfo|uomo|scura': 'man_elf_dark',
  'elfo|donna|chiara': 'woman_elf_light',
  'elfo|donna|chiara2': 'woman_elf_medium_light',
  'elfo|donna|media': 'woman_elf_medium',
  'elfo|donna|ambrata': 'woman_elf_medium_dark',
  'elfo|donna|scura': 'woman_elf_dark',
  'casual|uomo|chiara': 'man_tipping_hand_light',
  'casual|uomo|chiara2': 'man_tipping_hand_medium_light',
  'casual|uomo|media': 'man_tipping_hand_medium',
  'casual|uomo|ambrata': 'man_tipping_hand_medium_dark',
  'casual|uomo|scura': 'man_tipping_hand_dark',
  'casual|donna|chiara': 'woman_tipping_hand_light',
  'casual|donna|chiara2': 'woman_tipping_hand_medium_light',
  'casual|donna|media': 'woman_tipping_hand_medium',
  'casual|donna|ambrata': 'woman_tipping_hand_medium_dark',
  'casual|donna|scura': 'woman_tipping_hand_dark',
  'saluto|uomo|chiara': 'man_raising_hand_light',
  'saluto|uomo|chiara2': 'man_raising_hand_medium_light',
  'saluto|uomo|media': 'man_raising_hand_medium',
  'saluto|uomo|ambrata': 'man_raising_hand_medium_dark',
  'saluto|uomo|scura': 'man_raising_hand_dark',
  'saluto|donna|chiara': 'woman_raising_hand_light',
  'saluto|donna|chiara2': 'woman_raising_hand_medium_light',
  'saluto|donna|media': 'woman_raising_hand_medium',
  'saluto|donna|ambrata': 'woman_raising_hand_medium_dark',
  'saluto|donna|scura': 'woman_raising_hand_dark',
  'attesa|donna|chiara': 'pregnant_woman_light',
  'attesa|donna|chiara2': 'pregnant_woman_medium_light',
  'attesa|donna|media': 'pregnant_woman_medium',
  'attesa|donna|ambrata': 'pregnant_woman_medium_dark',
  'attesa|donna|scura': 'pregnant_woman_dark',
};

/// Gli abiti che non hanno un render tutto loro e ne prendono un altro.
const abitiSintetici = <String, String>{'polo': 'casual', 'camicia': 'casual'};

const personeDeiRitratti = <String>[
  'uomo',
  'donna',
  'neutro',
  'ragazzo',
  'ragazza',
  'anziano',
  'anziana',
];

/// Chi ha i capelli disegnati a parte: per gli altri c'e' una testa sola.
const personeConICapelli = <String>{'uomo', 'donna', 'neutro'};

const capelliDeiRitratti = <String>[
  'lisci',
  'barba',
  'ricci',
  'rossi',
  'bianchi',
  'biondi',
  'calvo',
];
const carnagioniDeiRitratti = <String>[
  'chiara',
  'chiara2',
  'media',
  'ambrata',
  'scura',
];
const vestitiDeiRitratti = <String>[
  'ufficio',
  'medico',
  'cuoco',
  'smoking',
  'velo',
  'pompiere',
  'poliziotto',
  'muratore',
  'operaio',
  'meccanico',
  'contadino',
  'pilota',
  'astronauta',
  'giudice',
  'supereroe',
  'scienziato',
  'insegnante',
  'studente',
  'informatico',
  'artista',
  'cantante',
  'guardia',
  'detective',
  'turbante',
  'supercattivo',
  'mago',
  'fata',
  'vampiro',
  'elfo',
  'casual',
  'saluto',
  'polo',
  'camicia',
  'attesa',
];
