// Generated by scripts/generate_build_info.py from the checked-out HEAD.
import "../src/sections/beta17-final-icon-polish-section.js";
import "../src/sections/beta-entry-section.js";
import "../src/sections/save-engine-section.js";
import "../src/sections/beta11-real-device-polish-section.js";
import "../src/sections/beta12-room-color-lock-section.js";
import "../src/sections/beta14-real-device-hotfix-section.js";
import "../src/sections/beta16-real-device-layout-section.js";
import "../src/sections/beta22-load-slots-hotfix-section.js";
import "../src/sections/beta24-energy-recovery-section.js";
import "../src/sections/beta25-real-device-fixes-section.js";
import "../src/sections/beta25-compatibility-section.js";
import "../src/sections/beta26-real-device-stability-section.js";
import "../src/sections/segnalazioni-section.js";
export const BUILD_INFO = Object.freeze({"generated":true,"integrationVersion":"1.4.28","dashboardVersion":"1.4.28","moduleVersion":14,"schemaVersion":4,"date":"2026-09-14T21:15:08+00:00","commit":"7274125e8d3195455d00587120c66f857bf71576","assetHash":"e4f8c1e0b95c3664"});
