// Generated by scripts/generate_build_info.py from the checked-out HEAD.
import "../src/sections/beta17-final-icon-polish-section.js";
import "../src/sections/beta-entry-section.js";
import "../src/sections/save-engine-section.js";
import "../src/sections/beta11-real-device-polish-section.js";
import "../src/sections/beta12-room-color-lock-section.js";
import "../src/sections/beta14-real-device-hotfix-section.js";
import "../src/sections/beta16-real-device-layout-section.js";
import "../src/sections/beta22-load-slots-hotfix-section.js";
import "../src/sections/beta24-energy-recovery-section.js";
import "../src/sections/beta25-real-device-fixes-section.js";
import "../src/sections/beta25-compatibility-section.js";
import "../src/sections/beta26-real-device-stability-section.js";
import "../src/sections/segnalazioni-section.js";
export const BUILD_INFO = Object.freeze({"generated":true,"integrationVersion":"1.4.19","dashboardVersion":"1.4.19","moduleVersion":14,"schemaVersion":4,"date":"2026-09-10T23:48:56+00:00","commit":"f01538e71eb917f8556f8458410e11090b078a8e","assetHash":"f994463389c1295b"});
